### PR TITLE
backends bugfixes, improvements and many more enhancements

### LINKED ISSUE #2304: centralized netdata and unique opentsdb tags per host
I'm trying to build a centralized netdata server that is receiving updates from 30-40 headless collector netdata instances.  I want it to write out to InfluxDB via the opentsdb interface, and I want it to add tags to that data.  The tags would reflect tags we use in our AWS environment, like "InstanceClass" or "Name".

Since the tags are defined in [backend] in netdata.conf, I don't see how the data from different hosts could be tagged differently.  I suspect that this is not possible (since the netdata child nodes probably aren't passing tags to the master).

Maybe the answer is to go straight to InfluxDB from the child nodes.  But I would really like to have a live netdata dashboard with all my nodes.  And I'd like to take advantage of netdata's handling of ephemeral nodes, which would be a huge benefit.

### LINKED ISSUE #2342: Not happy with kickstart script
It miss `--dont-start-it` from netdata-installer.sh and it downloads netdata source to `/usr/src/netdata` while I prefer `/opt/netdata` and old installation way respects source directory you run script from. More above I found out that non interactive installs cron job by default, and I do it manually. Also my-netdata.io just drops connections to several ips, or ISP blocks it.
Basically, I can restore [part of old install instructions](https://github.com/firehol/netdata/wiki/Installation/c2f0d2190e00ceae6564789c701b7f7f2db0eb76) as addition to current one from the old revision.
For example the way I do it now:
```
cd /opt/
git clone https://github.com/firehol/netdata.git --depth=1
cd netdata
curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh -i netdata (actually I install packages manually)
./netdata-installer.sh --dont-wait --dont-start-it
```
However I think better solution will be just to add `--dont-start-it` and `--src-dir=/opt/netdata` `--no-cron` to kickstarter script. Also it may be viable to add `--no-systemd`.
Ideas?

### LINKED ISSUE #2344: Discord Notifications
I installed the latest version of netdata with the kicstart script on EL7. When attempting to run _/usr/libexec/netdata/plugins.d/alarm-notify.sh test_ we receive the following.

```
# SENDING TEST CRITICAL ALARM TO ROLE: sysadmin
2017-06-15 17:07:12: alarm-notify.sh: ERROR: failed to send discord notification for: local.localdomain test.chart.test_alarm is CRITICAL to 'tech-only', with HTTP error code 400.
# FAILED

# SENDING TEST WARNING ALARM TO ROLE: sysadmin
2017-06-15 17:07:12: alarm-notify.sh: ERROR: failed to send discord notification for: local.localdomain test.chart.test_alarm is WARNING to 'tech-only', with HTTP error code 400.
# FAILED

# SENDING TEST CLEAR ALARM TO ROLE: sysadmin
2017-06-15 17:07:13: alarm-notify.sh: ERROR: failed to send discord notification for: local.localdomain test.chart.test_alarm is CLEAR to 'tech-only', with HTTP error code 400.
# FAILED
```

The same webhook runs for older versions that were setup and upgraded.

### LINKED ISSUE #2356: [BUG] Wrong selection in side menu after clicking an entry
Version: v1.6.0-553-g0d75bc6b_rolling
Browser: Safari Version 10.1.1 (12603.2.4)

Problem:
After clicking an entry in the Side menu the wrong menu item gets selected. (see Screenshot)

bildschirmfoto 2017-06-18 um 10 51 11

Memory was clicked and page jump works but the item above (processes) gets the selected menu item. This issue appears with all items.

### PR DESCRIPTION
**Pull request by ktsaou**
Added script `contrib/nc-backend.sh` that can be used to dump metrics generated by netdata to the console and a file. It can also be used as a fallback backend to cache the metrics on disk, when the time-series database goes offline. It works like this:

```
Usage:

    "./contrib/nc-backend.sh" start|stop PORT [BACKEND_HOST BACKEND_PORT]

    PORT          The port this script will listen
                  (configure netdata to use this as a second backend)

    BACKEND_HOST  The real backend host
    BACKEND_PORT  The real backend port

    This script can act as fallback backend for netdata.
    It will receive metrics from netdata, save them to
    /tmp/netdata-nc-backend-
    and once netdata reconnects to the real-backend, this script
    will push all metrics collected to the real-backend too and
    wait for a failure to happen again.

    Only one netdata can connect to this script at a time.
    If you need fallback for multiple netdata, run this script
    multiple times with different ports.

    You can run me in the background with this:

    screen -d -m "./contrib/nc-backend.sh" start PORT [BACKEND_HOST BACKEND_PORT]
```

---

Added more debugging information to help trace issue #2334 (still in progress)

---

Fixed #2344 (discord rejecting alarm notifications when the username is above 32 characters.

---

Fixed #2304 (host tags to be propaged between netdata servers while streaming)

---

Fixed #2342 (add more command line options to kickstart.sh)

---

Contributes to #2161 (do not enable `/lxc/*/ns/*` cgroups)

---

Fixed #2356 (dashboard main menu showing wrong item on click)

### CODE REVIEW

File: kickstart.sh [hunk 1]
```diff
@@ -304,8 +321,6 @@ git="$(which_cmd git)"
 NETDATA_SOURCE_DIR=
 if [ ! -z "${git}" -a -x "${git}" ]
 then
-    SOURCE_DST="/usr/src"
-
     [ ! -d "${SOURCE_DST}" ] && run ${sudo} mkdir -p "${SOURCE_DST}"
 
     if [ ! -d "${SOURCE_DST}/netdata.git" ]
```
Comment (cryptofuture) [inline kickstart.sh]: Why `if [ ! -d "${SOURCE_DST}/netdata.git" ]` but not just `netdata` is it really more viable? I think its pretty obvious source updates from git, but directory name with .git in name looks really alien.

Comment (ktsaou) [inline kickstart.sh]: The problem is that if you do `./kickstart.sh --src-dir /opt --install /opt` you will end up with a mess!
So, I thought it was better the source to be named `netdata.git` and the binary installation `netdata` and allow both in `/opt`.

Actually, I always try to name directories mirrored from git as `.git`. It helps me remember that this directory is something that can be updated with a `git pull`.

Comment (cryptofuture) [inline kickstart.sh]: That makes sense, I''ll move all another 4 netdata hosts to from `/opt/netdata` to `/opt/netdata.git`. Just hate inconsistency.
