### PR TITLE
web_log.chart squid part: restrict chars in mime-type

### LINKED ISSUE #3738: ERROR 405 with squid and web_logs plugin
After a while accessing netdata on proxy host with `web_logs` plugin enabled starts to fail with `ERROR 405: Cannot download charts index from server`. Getting json from `/api/v1/charts` and validating with <https://jsonlint.com/> shows that `web_log_squid.squid_mime_type` dimension became polluted like
this (json does not support commends, but lets pretend it does for a moment):

``` json
		"web_log_squid.squid_mime_type": {
			"id": "web_log_squid.squid_mime_type",
			"name": "web_log_squid.squid_mime_type",
			"type": "web_log_squid",
			"family": "squid_requests",
			"context": "web_log.squid_mime_type",
			"title": "Requests Per MIME Type (web_log_squid.squid_mime_type)",
			"priority": 60004,
			"plugin": "python.d.plugin",
			"module": "web_log",
			"enabled": true,
			"units": "requests/s",
			"data_url": "/api/v1/data?chart=web_log_squid.squid_mime_type",
			"chart_type": "stacked",
			"duration": 3996,
			"first_entry": 1526915280,
			"last_entry": 1526919276,
			"update_every": 1,
			"dimensions": {
				"text": {
					"name": "text"
				},
				"application": {
					"name": "application"
				},
				"image": {
					"name": "image"
				},
                                   # questionable entries
                                   "image%2Fjpeg": {
					"name": "image%2Fjpeg"
				},
				"charset=utf-8": {
					"name": "charset=utf-8"
				},
				"multipart": {
					"name": "multipart"
				},
				"pplication": {
					"name": "pplication"
				},
                                   # downright broken one
				"pdf"
				": { "
				name ": "
				pdf ""
			}
		},
		"green": null,
		"red": null,
		"alarms": {

		}
	},
```

Btw "pplication" above actually presents in log (log format is slightly custom, but error manifests itself with default log format too)

```
alex@proxy-vm:netdata# grep ' pplication' /apps/squid/logs/access.log | head -3
1526909289.570   5774 win-admin.m1.maxidom.ru TCP_MISS/200 3736081 GET http://download.support.xerox.com/pub/drivers/WC6505/drivers/winxp/ru/WorkCentre_6505_Win7_Vista_XP_PCL6_32_Russian.exe - FIRST_UP_PARENT/relay-ra pplication/x-msdownload
1526909326.435   5946 win-admin.m1.maxidom.ru TCP_MISS/200 4113409 GET http://download.support.xerox.com/pub/drivers/WC6505/drivers/winxpx64/ru/WorkCentre_6505_Win7_Vista_XP_PCL6_x64_Russian.exe - FIRST_UP_PARENT/relay-ra pplication/x-msdownload
1526909702.649   1692 win-admin.m1.maxidom.ru TCP_MISS/200 12315018 GET http://download.support.xerox.com/pub/drivers/WC7220_WC7225/drivers/win10x64/ar/WC72XX_5.433.16.0_PCL6_x64.exe - FIRST_UP_PARENT/relay-ra pplication/x-msdownload

alex@proxy-vm:netdata# grep 'image%2Fjpeg' /apps/squid/logs/access.log | head -3
1526893932.755    578 groms.m1.maxidom.ru TCP_MISS/200 37208 GET http://media.lpgenerator.ru/images/145563/strahovanie-meditsinskih-rashodov.jpg - FIRST_UP_PARENT/relay-ra image%2Fjpeg
1526893932.762    638 groms.m1.maxidom.ru TCP_MISS/200 65887 GET http://media.lpgenerator.ru/images/145563/100139138384347463.jpg - FIRST_UP_PARENT/relay-ra image%2Fjpeg
1526893932.764    587 groms.m1.maxidom.ru TCP_MISS/200 41558 GET http://media.lpgenerator.ru/images/145563/andrej-zabelin.jpg - FIRST_UP_PARENT/relay-ra image%2Fjpeg
```

and broken line is produced by some broken server

```
root@proxy-vm:netdata# grep 'pdf"' /apps/squid/logs/access.log | head -3
1526913153.076    222 proxy.n1.maxidom.ru TCP_MISS/200 130097 GET http://grafitnn.ru/pricelist/pdf - FIRST_UP_PARENT/relay-ra pdf"

alex@alex-mp:~$ curl -I http://grafitnn.ru/pricelist/pdf 2>&1 | grep Content-Type:
Content-Type: pdf";
```

Most probably need a litte bit more sanitisation for content-type

### PR DESCRIPTION
**Pull request by veksh**
Do not accept non-ascii chars (especially `"`) as part of Content-Type for squid access.log

fixes #3738

### CODE REVIEW

**Comment by l2isbad** [comment]
After this PR lines with _questionable_ and _broken_  content type will be considered as unmatched. Which is not good imo.

1. I see lambda func for dimension_id and dimension
https://github.com/firehol/netdata/blob/master/python.d/web_log.chart.py#L840-L841
We can replace bad symbols
2. Add additional check for `mime_type` and skip bad ones.
3. Replace the regex and make `mime_type` optional (`r' (?P<mime_type>[A-Za-z0-9-]+)?'`)

What do you think?

**Comment by veksh** [comment]
> After this PR lines with questionable and broken content type will be considered as unmatched. 

No, `(?P<mime_type>[A-Za-z0-9-]+)')` will match until first "bad" char (btw making `split('/') below redundant -- match will terminate on `/` too), so "image%2Fjpeg" will become "image" as expected.

Results from last hour on moderately busy proxy look like this:

contents

with culprits being

```
alex@proxy-vm:~$ grep ' Not' /apps/squid/logs/access.log | head -3
1526979337.788   3001 tamojna_1.m1.maxidom.ru TCP_MISS/404 611 GET http://dmg.digitaltarget.ru/1/175/i/i? - FIRST_UP_PARENT/relay-ra Not
1526982207.735   2993 mark5.m1.maxidom.ru TCP_MISS/404 709 GET http://dmg.digitaltarget.ru/1/1165/v/x? - FIRST_UP_PARENT/relay-ra Not
1526982223.106   3026 mark5.m1.maxidom.ru TCP_MISS/404 612 GET http://dmg.digitaltarget.ru/1/1165/v/x? - FIRST_UP_PARENT/relay-ra Not
alex@proxy-vm:~$ grep ' Content' /apps/squid/logs/access.log | head -3
1526970312.908      8 secdir1-s1.s1.maxidom.ru TCP_MISS/200 1147 GET http://static-ru.plista.com/image/logo_plista_small_AAAAAA.png - FIRST_UP_PARENT/relay-ra Content-type:
1526970846.342     59 tamoj-4.m1.maxidom.ru TCP_MISS/200 682 GET http://n.lady-click.com/st? - FIRST_UP_PARENT/relay-ra Content-type:
1526970846.353     58 tamoj-4.m1.maxidom.ru TCP_MISS/200 682 GET http://n.lady-click.com/st? - FIRST_UP_PARENT/relay-ra Content-type:
```

There is something some trash like this floating around in proxy log; this PR aims to tolerate not classify it :)

**Comment by l2isbad** [comment]
Yes, you are right :+1: 

Do we need all these `Content-Type` and `Not` ? I think no and `unmatched` dimension for mime_type is good idea.

@veksh ?

@ktsaou @Ferroin

**Comment by veksh** [comment]
> Do we need all these Content-Type and Not ? I think no and unmatched dimension for mime_type is good idea.

According to [wikipedia](https://en.wikipedia.org/wiki/Media_type) actual list of (case-insensitive) mime-types is quite short:

> application, audio, example, font, image, message, model, multipart, text and video

everything else is most probably an error, so 
- matcher could use `(?P<mime_type>[A-Za-z]*)`
- lambda below could be like

``` python
       ...
       mimes = ['application', 'audio', 'example', 'font', 'image', 'message', 'model', 'multipart', 'text', 'video']
       ...
            'mime_type': {
                'chart': 'squid_mime_type',
                'func_dim_id': lambda v: v if v in mimes else 'unmached'
                'func_dim': None}}

**Comment by veksh** [comment]
Oh, case-insensitivity :)

``` python

'func_dim_id': lambda v: str.lower(v) if str.lower(v) in mimes else 'unmached'

```

**Comment by l2isbad** [comment]
Yeah, something like that.
```
  'func_dim_id': lambda v: v if v in mimes else 'unmatched_mime_type'
  'func_dim': lambda v: v if v in mimes else 'unmached'
```

`dimension` - how it will look in the dashboard.

**Comment by l2isbad** [comment]
And `(?P<mime_type>[A-Za-z]+)` instead of `(?P<mime_type>[A-Za-z]*)`

**Comment by Ferroin** [comment]
I think it might make sense to make the dimension name `unknown` instead of `unmatched`, but that's just me..

Just to clarify, the regex being changed is just supposed to match the MIME type, and not include the subtype and suffix?  I'm not 100% certain from looking at the code whether that's the case or not, and if it needs to include the subtype and possibly also suffix, then it needs to be modified.

Beyond that though, LGTM.

**Comment by l2isbad** [comment]
`unknown` :+1: 

Yes, just the MIME type.

**Comment by veksh** [comment]
now checking against a list of known-good mime types

File: python.d/web_log.chart.py [hunk 1]
```diff
@@ -808,15 +809,15 @@ def check(self):
             return False
         self.storage['unique_all_time'] = list()
         self.storage['regex'] = re.compile(r'[0-9.]+\s+(?P<duration>[0-9]+)'
-                                           r' (?P<client_address>[\da-f.:]+)'
+                                           r' (?P<client_address>[\dA-Za-z.:_-]+)'
```
Comment (l2isbad) [inline python.d/web_log.chart.py]: `client_address`(IP address) is `[\da-f.:]+` not `[\dA-Za-z.:_-]+`
[These charts](https://github.com/firehol/netdata/blob/master/python.d/web_log.chart.py#L81-L92) will be misleading in case of hostnames instead of ip addresses.

File: python.d/web_log.chart.py [hunk 2]
```diff
@@ -808,15 +809,15 @@ def check(self):
...
                                            r' (?P<squid_code>[A-Z_]+)/'
                                            r'(?P<http_code>[0-9]+)'
                                            r' (?P<bytes>[0-9]+)'
                                            r' (?P<method>[A-Z_]+)'
                                            r' (?P<url>[^ ]+)'
                                            r' (?P<user>[^ ]+)'
-                                           r' (?P<hier_code>[A-Z_]+)/[\da-f.:-]+'
-                                           r' (?P<mime_type>[A-Za-z0-9-]+)')
+                                           r' (?P<hier_code>[A-Z_]+)/[\da-z.:-]+'
+                                           r' (?P<mime_type>[A-Za-z-]*)')
```
Comment (l2isbad) [inline python.d/web_log.chart.py]: `*` means that `mime_type` can be "" (empty `str`). I suggest to replace it with `+`.

Comment (l2isbad) [reply python.d/web_log.chart.py]: Well, i see 
`Also, some weird replies have content types ":" or even empty ones.`

https://wiki.squid-cache.org/Features/LogFormat

So `*` is ok.

Looks like we need to add empty line check to
https://github.com/firehol/netdata/blob/master/python.d/web_log.chart.py#L885-L886

File: python.d/web_log.chart.py (hunk 1 above)
Comment (veksh) [reply python.d/web_log.chart.py]: Sorry for sneaking host regexp there -- IP one is not useable with my log format.
I still failed to see what is so misleading in counting unique hostnames instead of IP addresses (and whole point of separate counts for unique hostnames, ipv4 and ipv6 adresses).

File: python.d/web_log.chart.py (hunk 2 above)
Comment (veksh) [reply python.d/web_log.chart.py]: > Looks like we need to add empty line check to

`func_dim_id` will be "unknown" with empty mime-type returned by regexp

**Comment by ktsaou** [comment]
Is this ready for merge?

**Comment by veksh** [comment]
I see nothing to add (or remove), but the final judgement is on @l2isbad as an author of original package.

**Comment by l2isbad** [comment]
> restrict chars in mime-type

i am not ok with replacing `client_address` regex

**Comment by veksh** [comment]
> i am not ok with replacing client_address regex

It would 
- act exactly the same way as previous "ip-only" in default squid configuration
- and break things for me (and other users preferring to have client host names in log)

> this is just wrong

It is hard to argue against that :)
Ok, I've put back "just ip" regexp for client.

**Comment by l2isbad** [comment]
> and break things for me (and other users) preferring to have client host names in log

We have to add custom_regex feature and add `hostnames` dimension to `clients` charts.

Changing `client_address` regex part looks as dirty workaround to me.

**Comment by ktsaou** [comment]
merged it.
