### PR TITLE
fix unnecessary calls to realloc()

### LINKED ISSUE #1048: SPEC file missing libuuid-devel
Hi,

Trying to build the RPM with mock (a tool to build it in a chroot).

The SPEC file is missing the libuuid-devel as a build dependency:

``
BuildRequires:	libuuid-devel
``

### PR DESCRIPTION
**Pull request by ktsaou**
also:

1. added memory allocations logger enabled with -DNETDATA_LOG_ALLOCATIONS=1
2. apps.plugin now reports virtual size of all applications, users and user groups
3. reduced the virtual memory size of netdata when it is linked against gcc, by setting MALLOC_ARENA_MAX (by default it is `1`, but there are configuration options to set it for netdata and for its plugins).
4. fixes #1048 (missing libuuid from netdata.spec)

### CODE REVIEW

**Comment by ktsaou** [comment]
@alonbl could you please check these too? With these, I think all autoconf related work is done. netdata does not use anything glibc specific that is not configured by autoconf.

File: src/apps_plugin.c [hunk 1]
```diff
@@ -66,23 +66,23 @@ struct target {
...
     unsigned long long statm_resident;
     unsigned long long statm_share;
-    unsigned long long statm_text;
-    unsigned long long statm_lib;
-    unsigned long long statm_data;
-    unsigned long long statm_dirty;
+    // unsigned long long statm_text;
+    // unsigned long long statm_lib;
+    // unsigned long long statm_data;
+    // unsigned long long statm_dirty;
```
Comment (alonbl) [inline src/apps_plugin.c]: please do not use C++ comments, always use --enable-pedantic to check.

File: src/common.h [hunk 2]
```diff
@@ -131,11 +131,25 @@ extern int  vsnprintfz(char *dst, size_t n, const char *fmt, va_list args);
 extern int  snprintfz(char *dst, size_t n, const char *fmt, ...) __attribute__ (( format (printf, 3, 4)));
 
 // memory allocation functions that handle failures
+#ifdef NETDATA_LOG_ALLOCATIONS
+#define strdupz(s) strdupz_int(__FILE__, __FUNCTION__, __LINE__, s)
+#define callocz(nmemb, size) callocz_int(__FILE__, __FUNCTION__, __LINE__, nmemb, size)
```
Comment (alonbl) [inline src/common.h]: __FUNCTION__ is non standard, you should detect it in autoconf, probably __func__ then __FUNCTION__ then fallback to define global __func__ with "", checkout if [1] helps.

[1] https://www.gnu.org/software/autoconf-archive/ax_c_var_func.html

**Comment by alonbl** [comment]
please reduce complexity, always call the *z using a macro and condition the implementation within.
you may also experience a severe multithread issues (if you are thread aware).
the overall implementation may suggest you want to use one of the alternate heap management libraries out there.

**Comment by ktsaou** [comment]
> please reduce complexity, always call the *z using a macro and condition the implementation within.

I thought it would be better to avoid passing all these parameters on production, but probably you are right: over-optimization.

> the overall implementation may suggest you want to use one of the alternate heap management libraries out there.

The funny thing is that netdata does not use memory allocation so much. It adapts its buffers on start, and this is it. No more allocations. The problem is that due to multi-threading, glibc uses several arenas, up to 5 times the memory allocated by netdata... Even with `MALLOC_ARENA_MAX=1` the heap in 1.5 - 2 times more than the allocated memory...

File: m4/ax_c_mallinfo.m4 [hunk 3]
```diff
@@ -0,0 +1,21 @@
...
+# Define HAVE_C_MALLINFO if mallinfo() works.
+AN_IDENTIFIER([mallinfo], [AC_C_MALLINFO])
+AC_DEFUN([AC_C_MALLINFO],
+[AC_CACHE_CHECK([for mallinfo], ac_cv_c_mallinfo,
+[AC_LINK_IFELSE(
+   [AC_LANG_SOURCE(
+      [[#include <malloc.h>
+        int main(int argc, char **argv) {
+          struct mallinfo mi = mallinfo();
+          printf("%d%d%d\n", mi.uordblks, mi.hblkhd, mi.arena);
```
Comment (alonbl) [inline m4/ax_c_mallinfo.m4]: this print is meaningless, but if you insist you must probably include stdio.
also... you should use AC_LANG_PROGRAM so first parameter is the include and the 2nd is the main body.

**Comment by alonbl** [comment]
On 1 October 2016 at 00:42, Costa Tsaousis <notifications@github.com> wrote:

>> the overall implementation may suggest you want to use one of the alternate heap management libraries out there.
>
> The funny thing is that netdata does not use memory allocation so much. It adapts its buffers on start, and this is it. No more allocations. The problem is that due to multi-threading, glibc uses several arenas, up to 5 times the memory allocated by netdata... Even with MALLOC_ARENA_MAX=1 the heap in 1.5 - 2 times more than the allocated memory...

but your implementation is not thread safe as far as I can see.

**Comment by ktsaou** [comment]
> but your implementation is not thread safe as far as I can see.

what did you see?

**Comment by alonbl** [comment]
On 1 October 2016 at 00:47, Costa Tsaousis <notifications@github.com> wrote:
>
> but your implementation is not thread safe as far as I can see.
>
> what did you see?

not sure I understand entire thing, but having global variable metrics
modified without locking may lead to unexpected results.

**Comment by ktsaou** [comment]
a! ok. These are not in production. They are just for debugging in `#ifdef` (I was trying to figure out what is happening with the heap). Even for these though, I plan to replace them with `__atomic_*` versions.

**Comment by alonbl** [comment]
On 1 October 2016 at 00:59, Costa Tsaousis <notifications@github.com> wrote:
>
> a! ok. These are not in production. They are just for debugging in #ifdef (I was trying to figure out what is happening with the heap). Even for these though, I plan to replace them with __atomic_* versions.
>

if these for debug, why don't you use valgid?

**Comment by ktsaou** [comment]
It does not report the glibc malloc arenas (or at least I couldn't find out how to report them). I have a production server where the netdata database is 500MB, but the netdata heap is 2GB. Overall the machine has overcommitted memory and I was trying to figure out what is happening.

I ended up reading everything about glibc memory allocation, arenas, et.al

Meanwhile I added all this code, which is currently disabled. It might be handy in the future.

File: m4/ax_c_mallinfo.m4 (hunk 3 above)
Comment (ktsaou) [inline m4/ax_c_mallinfo.m4]: I needed to make sure `struct mallinfo` has the right members. Without it, an incompatible mallinfo will give a false positive match and netdata will break to be linked.

Right?

Comment (ktsaou) [inline m4/ax_c_mallinfo.m4]: Can you help me with `AC_LANG_PROGRAM`. I tried to find an example, but couldn't find one. Should I put it inside `AC_LANG_SOURCE` or what?

**Comment by ktsaou** [comment]
> use one of the alternate heap management libraries out there.

Added jemalloc and tcmalloc in PR #1053 
They don't help...

**Comment by ktsaou** [comment]
Any other suggestions?

File: m4/ax_c_mallinfo.m4 (hunk 3 above)
Comment (alonbl) [inline m4/ax_c_mallinfo.m4]: Should be something like:

instead of the AC_LANG_SOURCE use the following:

AC_LANG_PROGRAM(
    [[#include <malloc.h>]],
    [[
        struct mallinfo mi = mallinfo();
        /* make sure that fields exists */
        mi.uordblks = 0;
        mi.hblkhd = 0;
        mi.arena = 0;
    ]]
)

AC_LANG_PROGRAM should be used in almost all cases, AC_LANG_SOURCE only in rare cases.
