### PR TITLE
nasty bug: char = -1; then char == -1 gives false; fixes #849

### LINKED ISSUE #849: QoS graph doesn't show up
I am not sure if this is actually a bug in the software, but as I followed the documentation on the wiki step by step there's probably at least an error over there.

So what I did. I first installed netdata, everything default.
Then I wrote a fireqos.conf that configures QoS for the device eth1 and applied it using fireqos start.
I verified it using fireqos status and restarted netdata expecting to see a QoS graph after a restart.

But the graph was missing.

Trying to identify the cause of the issue I checked the following:
tc-qos-helper.sh is running in the background
running tc-qos-helper.sh manually results in lots of output.

What can I do to get the graph to show up or what additional information do you need to narrow down the issue?

### PR DESCRIPTION
**Pull request by ktsaou**

### CODE REVIEW

File: src/plugin_tc.c [hunk 1]
```diff
@@ -242,7 +243,7 @@ static inline void tc_device_commit(struct tc_device *d) {
         return;
     }
 
-    if(unlikely(d->enabled == -1)) {
+    if(unlikely(d->enabled == (char)-1)) {
```
Comment (ktsaou) [inline src/plugin_tc.c]: this is the check

File: src/plugin_tc.c [hunk 2]
```diff
@@ -475,7 +487,7 @@ static inline struct tc_device *tc_device_create(char *id)
 
         d->id = strdupz(id);
         d->hash = simple_hash(d->id);
-        d->enabled = -1;
+        d->enabled = (char)-1;
```
Comment (ktsaou) [inline src/plugin_tc.c]: this is where it is set
