### PR TITLE
multi-threaded web server using poll(), added single threaded web server (using select())

### LINKED ISSUE #459: netdata starts logging before opening the log files and writes to stderr
Netdata starts logging information before opening the log files and thus, end up writing text to stderr which is not desirable when invoking netdata as a service.

Also, the text written to stderr is "lost" as it does not appear on the log files (error.log for instance)

Example
```
 * Starting real-time system monitoring netdata
16-05-27 04:31:07: INFO: netdata: Listening on all IPs (IPv6 and IPv4)
   ...done.
```
and editing /etc/netdata/netdata.conf 
```
[global]
  bind socket to IP = 127.0.0.1
```
makes netdata even more chatty
```
 * Starting real-time system monitoring netdata
16-05-27 04:31:25: ERROR: netdata: Failed to convert IP '127.0.0.1' to a valid IPv6 address. Disabling IPv6.
16-05-27 04:31:25: INFO: netdata: Listening on IP '127.0.0.1' (IPv4).
16-05-27 04:31:25: INFO: netdata: Managed to open an IPv4 socket on port 19999.
   ...done.
```
This also affects log rotation and you end up receiving a mail from cron every day with this very same text.

### PR DESCRIPTION
**Pull request by ktsaou**
- [x] added single threaded web server option (disabled by default). This web server has the limit of about 1000 concurrent sockets (a limitation of `select()`).

- [x] updated the multi-threaded web server (the default) to use `poll()` instead of `select()`. This web server can now handle any number of sockets, but it spawns a thread per socket, so `ulimit -n` has to be set properly for this to scale. The lockless design of the multi-threaded web server allows about 10.000 queries/second per core before seeing any CPU congestion.

- [x] fixes #459 to prevent logs on the console, when no errors are encountered. Errors will still log on the console.

- [x] installer now installs systemd service (and the uninstaller removes it) when the installer is run as root.

- [x] installer now restarts netdata using the `service` command if available. If falls back to the previous behavior if netdata cannot be started the official way.

### CODE REVIEW

File: src/web_client.c [hunk 1]
```diff
@@ -2047,95 +2108,123 @@ void *web_client_main(void *ptr)
...
-		tv.tv_sec = web_client_timeout;
-		tv.tv_usec = 0;
+		if(w->ifd == w->ofd) {
+			fds[0].fd = w->ifd;
+			fds[0].events = 0;
+			fds[0].revents = 0;
 
-		debug(D_WEB_CLIENT, "%llu: Waiting socket async I/O for %s %s", w->id, w->wait_receive?"INPUT":"", w->wait_send?"OUTPUT":"");
-		retval = select(fdmax+1, &ifds, &ofds, &efds, &tv);
+			if(w->wait_receive) fds[0].events += POLLIN;
```
Comment (simonnagl) [inline src/web_client.c]: `events` is a bit mask. I suggest to use `|=` here and the next three assignments. Now if `wait_recive` and `wait_send` are both true `events` is POLLIN + POLLOUT which is not correct.

**Comment by simonnagl** [comment]
I reviewed the code. No testing done. Very good work!

File: src/web_client.c (hunk 1 above)
Comment (ktsaou) [inline src/web_client.c]: Will do for completeness, but how `POLLIN + POLLOUT` is different from `POLLIN | POLLOUT` ? These are defined as bits in the spec (and in poll.h).

Comment (ktsaou) [inline src/web_client.c]: done

**Comment by ktsaou** [comment]
> I reviewed the code. No testing done. Very good work!

Thanks! I have done a million tests... I use loader.io to stress it to its limits...

File: src/web_client.c (hunk 1 above)
Comment (simonnagl) [inline src/web_client.c]: You are right. This was a fail in my thoughts. Anyways I think `|` is more clean to read. Thank you for changing it.

**Comment by ktsaou** [comment]
demo sites are now running this version.
tested the installer on different distros and versions. all seem good.
